baseurl                 = "http://nscodernightlondon.com/"               # Your domain name. Must end with "/"
languageCode            = "en-uk"
title                   = "NSCoder Night London"
theme                   = "sam"
googleAnalytics         = "UA-5015208-8"             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.ico"
#    pygmentsStyle       = "monokai"                     # https://help.farbox.com/pygments.html
#    pygmentsCodefences  = true
    homepage            = "Home"                        # What to call the home page link
#    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
#    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = "Call me Sam, a theme for Hugo."

# Metadata
    description         = "A monthly meetup for iOS, macOS, watchOS and tvOS developers in London."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/tn.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/nscoder-night-london"
    text = "NSCoder Night London"

[[params.mainMenu]]
    link = "/when-and-where"
    text = "When & Where"
    
[[params.mainMenu]]
    link = "/faq"
    text = "FAQ"
    
[[params.mainMenu]]
    link = "/contact"
    text = "Contact"
    